// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Block {
  id: string;
  slug: string | null;
  status: string;
  family: string;
  worker: string;
  initiated_by_role: "family" | "worker";
  block_status: "active" | "revoked";
  reason?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface FamilyProfile {
  id: string;
  slug: string | null;
  status: string;
  contact_name: string;
  contact_phone: string;
  support_categories: ("personal_care" | "community_access" | "capacity_building")[];
  support_needs_details?: string;
  hours_required: string;
  funding_type: "self_managed" | "plan_managed" | "ndia_managed";
  postcode: string;
  suburb?: string;
  state?: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "ACT" | "NT";
  diagnoses_conditions?: string;
  worker_preferences?: string;
  additional_notes?: string;
  has_support_coordinator?: boolean;
  content_flagged?: boolean;
  content_flag_reason?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Feedback {
  id: string;
  slug: string | null;
  status: string;
  interest: string;
  rater_role: "family" | "worker";
  reliability_rating: number;
  communication_rating: number;
  punctuality_rating: number;
  comment?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Interest {
  id: string;
  slug: string | null;
  status: string;
  family: string;
  worker: string;
  interest_status: "expressed" | "responded" | "closed";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Message {
  id: string;
  slug: string | null;
  status: string;
  interest: string;
  sender_role: "family" | "worker";
  body: string;
  content_flagged?: boolean;
  content_flag_reason?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Notification {
  id: string;
  slug: string | null;
  status: string;
  event_type: "interest_received" | "credential_expiring" | "message_received" | "search_alert";
  recipient_role: "family" | "worker";
  recipient_family?: string;
  recipient_worker?: string;
  related_interest?: string;
  body: string;
  read_at?: string;
  email_sent?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ReliabilityIncident {
  id: string;
  slug: string | null;
  status: string;
  interest: string;
  reported_by_role: "family" | "worker";
  incident_type: "cancellation" | "no_show";
  occurred_at: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Report {
  id: string;
  slug: string | null;
  status: string;
  family: string;
  worker: string;
  reporter_role: "family" | "worker";
  reason: string;
  report_status: "open" | "reviewed" | "actioned";
  resolution_notes?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface WorkerProfile {
  id: string;
  slug: string | null;
  status: string;
  full_name: string;
  date_of_birth: string;
  contact_phone: string;
  postcode: string;
  suburb?: string;
  state?: "NSW" | "VIC" | "QLD" | "WA" | "SA" | "TAS" | "ACT" | "NT";
  employment_structure: "independent_abn" | "subcontractor" | "employed_by_provider";
  abn?: string;
  subcontractor_details?: string;
  provider_company_details?: string;
  years_experience: number;
  preferred_client_types: ("children" | "adults" | "seniors" | "complex_needs" | "physical_disability" | "psychosocial_disability" | "autism")[];
  preferred_age_ranges?: ("0_17" | "18_65" | "65_plus")[];
  hours_available: string;
  resume: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  liability_insurance_details: string;
  drivers_licence: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  emergency_contact_name: string;
  emergency_contact_phone: string;
  wwcc_number: string;
  wwcc_expiry_date: string;
  wwcc_document: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  ndis_screening_number: string;
  ndis_screening_expiry_date: string;
  ndis_screening_document: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  police_check_number: string;
  police_check_expiry_date: string;
  police_check_document: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  review_status: "pending_review" | "approved" | "rejected";
  rejection_reason?: string;
  subscription_status: "inactive" | "active" | "past_due" | "cancelled";
  subscription_renews_at?: string;
  content_flagged?: boolean;
  content_flag_reason?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    blocks: Block;
    family_profiles: FamilyProfile;
    feedback: Feedback;
    interests: Interest;
    messages: Message;
    notifications: Notification;
    pages: Page;
    posts: Post;
    reliability_incidents: ReliabilityIncident;
    reports: Report;
    worker_profiles: WorkerProfile;
  }
}